FreelancerWebApp/Models/Comment.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace FreelancerWebApp.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public string text { get; set; }
        public DateTime Created { get; set; }
        public int rate { get; set; }

        [ForeignKey("job")]
        [DefaultValue(1)]
        public int JobId { get; set; }
        [ValidateNever]
        public job job { get; set; }

        [ForeignKey("ownerUser")]
        [DefaultValue(1)]
        public int ownerUserId { get; set; }
        [ValidateNever]
        public user ownerUser { get; set; }
        public int freelancerUserID { get; set; }
        public Comment()
        {
        
        }
    }
}

FreelancerWebApp/Models/profile.cs
namespace FreelancerWebApp.Models
{
    public class profile
    {
        public int Id { get; set; }

        public string UserName { get; set; }

        public string Email { get; set; }

        public profile()
        {
                
        }
    }
}

FreelancerWebApp/ViewModels/CommentViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace FreelancerWebApp.ViewModels
{
    public class CommentViewModel
    {
        [ValidateNever]
        public int Id { get; set; }
        [Required(ErrorMessage = "Comment can't be empty.")]
        public string text { get; set; }
        public DateTime Created { get; set; }
        public int rate { get; set; }
        public int JobId { get; set; }
        public int UserId { get; set; }
    }
}

FreelancerWebApp/Controllers/jobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreelancerWebApp.Data;
using FreelancerWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.Data.SqlClient;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using AutoMapper;
using FreelancerWebApp.ViewModels;
using Microsoft.Extensions.FileProviders;
using System.Web;


namespace FreelancerWebApp.Controllers
{
    public class jobsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IHostingEnvironment _env;
        public static string filepaths = "asd";
        private readonly IMapper _mapper;
        private readonly IFileProvider _fileProvider;

        public jobsController(ApplicationDbContext context, IHostingEnvironment env, IMapper mapper, IFileProvider fileProvider)
        {
            _context = context;
            _env = env;
            _mapper = mapper;
            _fileProvider = fileProvider;
        }

        // GET: jobs
        public IActionResult Index()
        {
            var Job = _context.job.ToList();

            return View(_mapper.Map<List<JobViewModel>>(Job));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> removefreelancer(int? id)
        {
            var job = _context.job.FirstOrDefault(x => x.Id == id);
            job.Freelancer_ID = "0";
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!jobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Profile", "Home");
            }
            return RedirectToAction("Profile", "Home");
        }

        // GET: jobs/ShowSearchFrom
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        // Post: jobs/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.job.Where(j=>j.Job_Title.Contains(SearchPhrase)).ToListAsync()); //filtering 
        }

        // GET: jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.job == null)
            {
                return NotFound();
            }

            var job = await _context.job
                .FirstOrDefaultAsync(m => m.Id == id);
            var jobb = await _context.job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewBag.userid = User.Identity.Name;

            var JobMapped = _mapper.Map<JobViewModel>(jobb);


            return View(JobMapped);
        }

        // GET: jobs/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.userid = User.Identity.Name;
            ViewBag.datenow = DateTime.UtcNow;
            ViewBag.Category = new SelectList(new List<categorySelectList>()
            {
                new(){Data="Graphic Design", Value="Graphic Design"},
                new(){Data="Text", Value="Text"},
                new(){Data="Software", Value="Software"}
            }, "Value", "Data");
            return View();
        }

        // POST: jobs/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobAddViewModel newJob)
        {
            var Owner_user = _context.user.FirstOrDefault(x=> x.user_email == newJob.Owner_ID);
           if(Owner_user.Money < newJob.Offered_Price)
            {
                TempData["Credit"] = "false";
                return RedirectToAction(nameof(jobsController.Create));
            }

            if (ModelState.IsValid)
            {
                var root = _fileProvider.GetDirectoryContents("wwwroot");
                var UploadedFile = root.First(x => x.Name == "JobPhotos");
                var randomFileName = Guid.NewGuid() + Path.GetExtension(newJob.JobImage.FileName);
                var path = Path.Combine(UploadedFile.PhysicalPath, randomFileName);
                using var stream = new FileStream(path, FileMode.Create);

                newJob.JobImage.CopyTo(stream);

                var Job = _mapper.Map<job>(newJob);

                Job.Job_Photo_Path = randomFileName;

                Job.Confirmed = false;

                _context.Add(Job);
                await _context.SaveChangesAsync();
                TempData["status"] = "Job published successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(newJob);
        }

        // GET: jobs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            var existJob = _context.job.Find(id);

            ViewBag.ColorSet = new SelectList(new List<categorySelectList>()
            {
                new(){Data="Graphic Design", Value="GraphicDesign"},
                new(){Data="Text", Value="Text"},
                new(){Data="Software", Value="Software"}
            }, "Value", "Data", existJob.Job_Category);



            if (id == null || _context.job == null)
            {
                return NotFound();
            }

            var job = await _context.job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewBag.userid = User.Identity.Name;
            return View(job);
        }

        // POST: jobs/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                    TempData["status"] = "Job updated successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!jobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: jobs/Deliver/5
        [Authorize]
        public async Task<IActionResult> Deliver(int? id)
        {
            
            if (id == null || _context.job == null)
            {
                return NotFound();
            }

            var job = await _context.job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<JobViewModel>(job));
        }


        //public IActionResult UploadDone(int id, IFormFile fileUploadinput, [Bind("Id,Job_Title,Job_Category,Job_Description,Offered_Price,Day,Owner_ID,Freelancer_ID,Deliver_File_Path")] job job)
        // POST: jobs/Deliver/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UploadDone(int id, JobViewModel job)
        {
            var root = _fileProvider.GetDirectoryContents("wwwroot");
            var UploadedFile = root.First(x => x.Name == "UploadedFiles");
            var randomFileName = Guid.NewGuid() + Path.GetExtension(job.File.FileName);
            var path = Path.Combine(UploadedFile.PhysicalPath, randomFileName);
            using var stream = new FileStream(path, FileMode.Create);

            job.File.CopyTo(stream);

            var JobDone = _mapper.Map<job>(job);
            JobDone.Deliver_File_Path = randomFileName;
            JobDone.Confirmed = false;

            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(JobDone);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!jobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }



        // GET: jobs/getJob/5
        [Authorize]
        public async Task<IActionResult> getJob(int? id)
        {
            if (id == null || _context.job == null)
            {
                return NotFound();
            }

            var job = await _context.job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewBag.userid = User.Identity.Name;
            return View(job);
        }

        // POST: jobs/getJob/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> getJob(int id,job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

FreelancerWebApp/Views/Shared/ViewComponents/CommentViewComponent.cs
using AutoMapper;
using FreelancerWebApp.Data;
using Microsoft.AspNetCore.Mvc;
using FreelancerWebApp.ViewModels;
using System;
using System.Linq;

namespace FreelancerWebApp.Views.Shared.ViewComponents
{
    public class CommentViewComponent:ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CommentViewComponent(ApplicationDbContext context,IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var list = _context.Comment.Select(x => new CommentListComponentViewModel()
            {
                Comment = x.text,
                userName = x.ownerUser.user_email,
                freelancerName = x.job.Freelancer_ID
            }).ToList();
            //ViewBag.jobId = jobId;
            //ViewBag.Date=DateTime.Now;
            return View(list);
        }
    }
}

FreelancerWebApp/Views/Home/Comment.cshtml
@model CommentViewModel
<@*div class="container">
    @await Component.InvokeAsync("Comment")
</div>*@

<style type="text/css">
.likecontainer {
    padding: 25px;
    box-shadow: 0 2px 8px rgba(0,0,0, 0.1);
    border-radius: 30px;
    background-color: #ffffff;
}
</style>

<div class="container">
    <div class="row gx-5">
        <div class="col-lg-8 mb-5 mb-lg-0 my-5">
            <div class="likecontainer">
                <form asp-action="Comment">
                    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                    <input type="hidden" asp-for="JobId" value="@ViewBag.jobId" />
                    <span asp-validation-for="JobId" class="text-danger"></span>
                    <input type="hidden" asp-for="UserId" value="1" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                    <input type="hidden" asp-for="Created" value="@ViewBag.Date" />
                    <span asp-validation-for="Created" class="text-danger"></span>
                    <input type="hidden" asp-for="Id" value="" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                    Rate
                    <div class="row">
                        <div class="col col-lg-1">
                            <input type="radio" id="age1" name="rate" value="1" asp-for="rate">
                            <label for="rate1">1</label><br>
                        </div>
                        <div class="col col-lg-1">
                            <input type="radio" id="age2" name="rate" value="2" asp-for="rate">
                            <label for="rate2">2</label><br>
                        </div>
                        <div class="col col-lg-1">
                            <input type="radio" id="age3" name="rate" value="3" asp-for="rate">
                            <label for="rate3">3</label><br>
                        </div>
                        <div class="col col-lg-1">
                            <input type="radio" id="age4" name="rate" value="4" asp-for="rate">
                            <label for="rate1">4</label><br>
                        </div>
                        <div class="col col-lg-1">
                            <input type="radio" id="age5" name="rate" value="5" asp-for="rate">
                            <label for="rate1">5</label><br>
                        </div>
                        <span asp-validation-for="rate" class="text-danger"></span>
                        <div class="form-group py-2">
                            <label asp-for="text">Comment</label>
                            <textarea asp-for="text" class="form-control my-2" placeholder="Comment" id="floatingTextarea" style="height:100px"></textarea>
                            <span asp-validation-for="text" class="text-danger"></span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary my-2">Submit</button>
                </form>
            </div>
        </div>
        <div class="col-lg-4 mb-5 mb-lg-0 my-5">
            <div class="likecontainer">
                <div class="text-center">
                    <h3 class="text-center">Usefull Tips</h3>
                    <h4> </h4>
                    <hr />
                </div>
                <p><strong>1.</strong> Rate the delivery based on your experinece with this freelancer.</p>
                <p><strong>2.</strong> Set a comment to evaluate and commentate all the experience, such as product and freelancer.</p>
                <br />
                <br />
                <br />
            </div>
            <br />
            <br />
            <br />
        </div>
    </div>
</div>

FreelancerWebApp/Views/Home/Deliver.cshtml
@model FreelancerWebApp.Models.job


<div class="container">
    <form asp-controller="Home" asp-action="UploadDone" enctype="multipart/form-data" method="post">
        <div class="form-group">
            <input type="number" name="jobNo"/>
        </div>
        <div class="form-group">
            <input type="file" name="fileUploadinput"/>
        </div>
        <div class="form-group">
            <button type="submit">Deliver</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FreelancerWebApp/Views/Home/Index.cshtml
@model IEnumerable<FreelancerWebApp.Models.job>
@{
    ViewData["Title"] = "Home";
}
<header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="~/Photos/freelancer2.png" alt="..." style="height:400px" /></div>
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">
                        Welcome To <br />
                        <span style="color: #ffbb33;">Freelancer.com</span>
                    </h1>
                    <p class="lead fw-normal text-white-50 mb-4">Best Freelancer Website In The Universe</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4" asp-controller="jobs" asp-action="Create">Get Started</a>
                        <a class="btn btn-outline-light btn-lg px-4 me-sm-3" href="#features">Features</a>
                        <a class="btn btn-outline-light btn-lg px-4 me-sm-3" href="#posts">Posts</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="py-5" id="features">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0">A better way to start building.</h2></div>
            <div class="col-lg-8">
                <div class="row gx-5 row-cols-1 row-cols-md-2">
                    <div class="col mb-5 h-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-collection-fill" viewBox="0 0 16 16">
                            <path d="M0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zM2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3zm2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1z" />
                        </svg>
                        <h2 class="h5">Post a Job</h2>
                        <p class="mb-0">Post your job with its details, price and day.</p>
                    </div>
                    <div class="col mb-5 h-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z" />
                            <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z" />
                        </svg>
                        <h2 class="h5">Find best freelancers</h2>
                        <p class="mb-0">In the site, you can find best freelancers. Your jobs will done perfectly</p>
                    </div>
                    <div class="col mb-5 mb-md-0 h-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z" />
                            <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z" />
                            <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z" />
                            <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z" />
                        </svg>
                        <h2 class="h5">Earn Money</h2>
                        <p class="mb-0">Get the jobs whatever fits you. And earn money</p>
                    </div>
                    <div class="col h-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-toggles2" viewBox="0 0 16 16">
                            <path d="M9.465 10H12a2 2 0 1 1 0 4H9.465c.34-.588.535-1.271.535-2 0-.729-.195-1.412-.535-2z" />
                            <path d="M6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 1a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm.535-10a3.975 3.975 0 0 1-.409-1H4a1 1 0 0 1 0-2h2.126c.091-.355.23-.69.41-1H4a2 2 0 1 0 0 4h2.535z" />
                            <path d="M14 4a4 4 0 1 1-8 0 4 4 0 0 1 8 0z" />
                        </svg>
                        <h2 class="h5">Gain Experience</h2>
                        <p class="mb-0">To do jobs and improve yourself if you are new in the sector. Or be free and gain your life here.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="py-5 bg-light" id="posts">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10 col-xl-7">
                <div class="text-center">
                    <div class="fs-4 mb-4 fst-italic">
                        "If you hire people just because they can do a job,
                        they’ll work for your money. But if you hire people who believe what you believe, they’ll work for you with blood and sweat and tears."
                    </div>
                    <div class="d-flex align-items-center justify-content-center">
                        <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                        <div class="fw-bold">
                            Simon Sinek
                            <span class="fw-bold text-primary mx-1">/</span>
                            American Author
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Jobs</h2>
                    <p class="lead fw-normal text-muted mb-5">There are few example of jobs, below.</p>
                </div>
            </div>
        </div>

        <div class="row gx-5">
            @{
                var counter = 3;
            }
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-5">
                    <div class="card h-100 shadow border-0">
                        <img class="card-img-top" src="/JobPhotos/@(item.Job_Photo_Path)" alt="..." />
                        <div class="card-body p-4">
                            <div class="badge bg-primary bg-gradient rounded-pill mb-3">@Html.DisplayFor(modelItem => item.Job_Category)</div>
                            <a class="text-decoration-none link-dark stretched-link" asp-controller="jobs" asp-action="Details" asp-route-id="@item.Id"><h4 class="card-title mb-3">@Html.DisplayFor(modelItem => item.Job_Title)</h4></a>
                            <p class="card-text mb-0">@Html.DisplayFor(modelItem => item.Job_Description)</p>
                        </div>
                        <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                            <div class="d-flex align-items-end justify-content-between">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                    <div class="small">
                                        <div class="fw-bold">@Html.DisplayFor(modelItem => item.Owner_ID)</div>
                                        <div class="text-muted">Limit: @Html.DisplayFor(modelItem => item.Day) Day &middot; <span class="text-success">@Html.DisplayFor(modelItem => item.Offered_Price)$</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                counter--;
                if (counter == 0)
                {
                    break;
                }
            }

            <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
                <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
                    <div class="mb-4 mb-xl-0">
                        <div class="fs-3 fw-bold text-white">Sign Up and post job or earn money.</div>
                        <div class="text-white-50">Easily sign up to site</div>
                    </div>
                    <div class="ms-xl-4">
                        <div class="input-group mb-2">
                            <input class="form-control" type="text" placeholder="Email address..." aria-label="Your email address..." aria-describedby="button-newsletter" />
                            <button class="btn btn-outline-light" id="button-newsletter" type="button"><a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Sign Up</a></button>
                        </div>
                        <div class="small text-white-50">We care about privacy, and will never share your data.</div>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</section>

<script src="~/js/scripts.js"></script>

FreelancerWebApp/Views/Home/Reviews.cshtml
@model List<UserListReviewViewModel>
<header class="bg-dark py-2">
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto " style="color:#ffbb33;">
                <h1 class="display-5 fw-bolder mb-2">Reviews</h1>
                <p class="fw-bolder text-white">You can see the reviews of the jobs and see the references</p>
            </div>
        </div>
    </section>
</header>

<div class="container py-5">
    <ul class="list-group">
        @foreach(var item in Model)
        {
            <li class="list-group-item">
                <a class="nav-link text-black" asp-controller="Home" asp-action="ReviewsOf" asp-route-id="@item.Id">@item.user_email</a>
            </li>
        }
    </ul>
</div>

FreelancerWebApp/Views/Home/ReviewsOf.cshtml
@model List<CommentListComponentViewModel>

@{
    var counter = 0;
    var toplam = 0;
    double averageRate = 0.0;
    @foreach (var item in Model)
    {
        counter++;
        toplam += item.rate;
    }
    if (counter != 0)
    {
        averageRate = (double)toplam / counter;
    }
}

<header class="bg-dark py-2">
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto " style="color:#ffbb33;">
                <h1 class="display-5 fw-bolder mb-2">Reviews</h1>
                <h4>@ViewBag.userName~@ViewBag.userEmail</h4>
                <p class="fw-bolder text-white">You can see @ViewBag.userEmail 's reviews of its works</p>
                <div style="text-align:center;">
                    @if(counter>0)
                    {
                        if (@averageRate.ToString().Length>3)
                        {
                            <p>@counter job has been done so far with @averageRate.ToString().Substring(0,3) average rate.</p>
                        }
                        else
                        {
                            <p>@counter job has been done so far with @averageRate average rate.</p>
                        }

                    }
                    
                </div>
            </div>
        </div>
    </section>
</header>

<div class="container py-5">
    <ul class="list-group">
        @foreach (var item in Model)
        {
            <li class="list-group-item py-3">
                <div class="row">
                    <div class="col-10">
                        <h4>@item.jobName</h4>
                        @item.Comment
                    </div>
                    <div class="col-2">
                        <div class="row" style="text-align:right;">
                            ~@item.userName
                        </div>
                        <div class="row" style="text-align:right">
                            Rate: @item.rate*
                        </div>
                    </div>
                </div>
            </li>
        }
        @if (counter == 0)
        {
            <div class="alert alert-danger">
                <p>There is no comment for this user (@ViewBag.userEmail)</p>
            </div>
        }
    </ul>
</div>